### ISSUE TITLE
Error running via Docker

### ISSUE THREAD

**Issue by blakestoddard** [segmentio/specs#32]
Hi!

When I try to run Specs using a docker command like so:

```
docker run -e "AWS_ACCESS_KEY=<snip>" -e "AWS_SECRET_ACCESS_KEY=<snip>" -e "AWS_REGION=us-east-1" -e "AWS_SESSION_TOKEN=<snip>" -p 3000:3000 segment/specs
```

I get the following error, which results in a forever-spinning loading icon on the homepage of Specs:

```
cache error: TimeoutError: Missing credentials in config
    at ClientRequest.<anonymous> (/src/node_modules/aws-sdk/lib/http/node.js:56:34)
    at ClientRequest.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:593:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:333:8)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

Any ideas? I tried doing a local version not using Docker using `make server` and `make dev-server`, but that gives me a different error that appears to be syntax related with Javascript.

**Comment by calvinfo** [comment]
That's not good–have you tried running without the session token? I know it depends on whether you've actually created a role for that or not which uses it.

**Comment by blakestoddard** [comment]
Just tried without, same error:
`docker run -e "AWS_ACCESS_KEY=<snip>" -e "AWS_SECRET_ACCESS_KEY=<snip>" -e "AWS_REGION=us-east-1" -p 3000:3000 segment/specs`

```
cache error: TimeoutError: Missing credentials in config
    at ClientRequest.<anonymous> (/src/node_modules/aws-sdk/lib/http/node.js:56:34)
    at ClientRequest.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:593:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:333:8)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

(this was tried with my own non-rotating IAM access keys as well as with temporary ones using `aws sys get-session-token`)

**Comment by akramhussein** [comment]
Just wondering if a resolution was found for this as I'm experiencing the same.

**Comment by blakestoddard** [comment]
@akramhussein & @calvinfo: This doesn't appear to be an issue in the most recent image that is on Docker Hub. Going to close this out.
